plugins:
  twitch_sidebar_enabled:
    client: true
    default: true
  twitch_sidebar_title:
    client: true
    default: "Live Streams"
  twitch_sidebar_user:
    client: true
    default: "Roragok"
